### ISSUE TITLE
ease adoption by enterprises

### ISSUE THREAD

**Issue by ilatypov** [jsdom/whatwg-mimetype#2]
WTFPL shows “lack of warranty disclaimer, very vague rights grant”, according to Google’s recommendation for employee contributors, https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed

I wonder if MIT or another top-5 OSI approved license could help in adopting this npm module by enterprises?

**Comment by nkothari-zz** [comment]
@domenic - Possible to dual-license this with MIT?

**Comment by domenic** [comment]
Fixed by #6.
