### ISSUE TITLE
Provide esm version

### ISSUE THREAD

**Issue by tobiasdiez** [jsdom/whatwg-mimetype#25]
With more and more build tools (vite, nuxt, etc) going towards an esm-first build, it would be nice if a proper [esm interface](https://nodejs.org/api/esm.html) could be provided, i.e. transpile and distribute esm version, including correct [export](https://nodejs.org/api/packages.html#conditional-exports) declaration in `package.json`.

**Comment by domenic** [comment]
I'm not interested in moving the jsdom ecosystem to esm at this time.
